package net.kineticdevelopment.arcana.client.models.sins;

import net.minecraft.client.renderer.entity.model.EntityModel;
import net.minecraft.client.renderer.entity.model.RendererModel;
import net.minecraft.entity.Entity;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.api.distmarker.OnlyIn;

@OnlyIn(Dist.CLIENT)
public class EnvyModel<T extends Entity> extends EntityModel<T> {
    public RendererModel Head;
    public RendererModel Body;
    public RendererModel RightRornBase;
    public RendererModel LeftRornBase;
    public RendererModel Teeth;
    public RendererModel RightHornEnd;
    public RendererModel LeftHornEnd;
    public RendererModel BodyExtensionY;
    public RendererModel BodyExtensionZ;
    public RendererModel BodyBottom;
    public RendererModel Chains;
    public RendererModel FrontRightElbow;
    public RendererModel BackRightElbow;
    public RendererModel FrontLeftElbow;
    public RendererModel BackLeftElbow;
    public RendererModel LeftHanging;
    public RendererModel RightHanging;
    public RendererModel FrontHanging;
    public RendererModel BackHanging;
    public RendererModel FRBell;
    public RendererModel FLBell;
    public RendererModel BRBell;
    public RendererModel BLBell;
    public RendererModel ChainFrontLeft;
    public RendererModel ChainFrontRight;
    public RendererModel ChainRightFront;
    public RendererModel ChainRightBack;
    public RendererModel ChainRightFront_1;
    public RendererModel ChainBackRight;
    public RendererModel ChainBackLeft;
    public RendererModel ChainLeftBack;
    public RendererModel ChainLeftFront;
    public RendererModel FrontRightPalm;
    public RendererModel FrontRightFinger1;
    public RendererModel FrontRightThumb;
    public RendererModel FrontRightFinger2;
    public RendererModel FrontRightFinger1End;
    public RendererModel FrontRightFinger2End;
    public RendererModel FrontRightPalm_1;
    public RendererModel BackRightFinger1;
    public RendererModel BackRightThumb;
    public RendererModel BackRightFinger2;
    public RendererModel BackRightFinger1End;
    public RendererModel BackRightFinger2End;
    public RendererModel FrontLeftPalm;
    public RendererModel FrontLeftFinger1;
    public RendererModel FrontLeftThumb;
    public RendererModel FrontLeftFinger2;
    public RendererModel FrontLeftFinger1End;
    public RendererModel FrontLeftFinger2End;
    public RendererModel BackLeftPalm;
    public RendererModel BackLeftFinger1;
    public RendererModel BackLeftThumb;
    public RendererModel BackLeftFinger2;
    public RendererModel BackLeftFinger1End;
    public RendererModel BackLeftFinger2End;

    public EnvyModel() {
        this.textureWidth = 64;
        this.textureHeight = 64;
        this.BRBell = new RendererModel(this, 0, 0);
        this.BRBell.setRotationPoint(1.0F, 0.0F, 9.0F);
        this.BRBell.addBox(-2.0F, 1.0F, 0.0F, 2, 2, 2, 0.0F);
        this.BackRightThumb = new RendererModel(this, 8, 2);
        this.BackRightThumb.setRotationPoint(0.0F, 5.0F, 0.0F);
        this.BackRightThumb.addBox(0.0F, 0.0F, -2.0F, 2, 1, 2, 0.0F);
        this.LeftHornEnd = new RendererModel(this, 60, 56);
        this.LeftHornEnd.mirror = true;
        this.LeftHornEnd.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.LeftHornEnd.addBox(6.0F, -8.0F, -0.5F, 1, 4, 1, 0.0F);
        this.BackLeftElbow = new RendererModel(this, 0, 0);
        this.BackLeftElbow.setRotationPoint(4.0F, 2.0F, 4.0F);
        this.BackLeftElbow.addBox(0.0F, 0.0F, 0.0F, 0, 0, 0, 0.0F);
        this.setRotateAngle(BackLeftElbow, 0.0F, 0.0F, -0.3141592653589793F);
        this.FRBell = new RendererModel(this, 0, 0);
        this.FRBell.setRotationPoint(1.0F, 0.0F, 1.0F);
        this.FRBell.addBox(-2.0F, 1.0F, -2.0F, 2, 2, 2, 0.0F);
        this.Teeth = new RendererModel(this, 50, 62);
        this.Teeth.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Teeth.addBox(-1.0F, -1.0F, -3.0F, 2, 1, 1, 0.0F);
        this.FrontRightFinger1 = new RendererModel(this, 0, 13);
        this.FrontRightFinger1.setRotationPoint(0.5F, 8.5F, 0.0F);
        this.FrontRightFinger1.addBox(-0.5F, -0.5F, -1.0F, 2, 1, 1, 0.0F);
        this.FrontLeftFinger2End = new RendererModel(this, 0, 10);
        this.FrontLeftFinger2End.mirror = true;
        this.FrontLeftFinger2End.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.FrontLeftFinger2End.addBox(-2.5F, -1.5F, 0.0F, 1, 2, 1, 0.0F);
        this.FrontRightElbow = new RendererModel(this, 0, 0);
        this.FrontRightElbow.setRotationPoint(-4.0F, 2.0F, -4.0F);
        this.FrontRightElbow.addBox(0.0F, 0.0F, 0.0F, 0, 0, 0, 0.0F);
        this.setRotateAngle(FrontRightElbow, 0.0F, 0.0F, 0.3141592653589793F);
        this.FrontLeftElbow = new RendererModel(this, 0, 0);
        this.FrontLeftElbow.setRotationPoint(4.0F, 2.0F, -4.0F);
        this.FrontLeftElbow.addBox(0.0F, 0.0F, 0.0F, 0, 0, 0, 0.0F);
        this.setRotateAngle(FrontLeftElbow, 0.0F, 0.0F, -0.3141592653589793F);
        this.ChainFrontLeft = new RendererModel(this, 44, 48);
        this.ChainFrontLeft.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.ChainFrontLeft.addBox(0.5F, 1.0F, -4.0F, 3, 16, 0, 0.0F);
        this.BodyExtensionY = new RendererModel(this, 36, 31);
        this.BodyExtensionY.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.BodyExtensionY.addBox(-5.0F, 1.0F, -2.0F, 10, 1, 4, 0.0F);
        this.FrontLeftFinger1 = new RendererModel(this, 0, 13);
        this.FrontLeftFinger1.mirror = true;
        this.FrontLeftFinger1.setRotationPoint(0.5F, 8.5F, 0.0F);
        this.FrontLeftFinger1.addBox(-1.5F, -0.5F, -1.0F, 2, 1, 1, 0.0F);
        this.RightHornEnd = new RendererModel(this, 60, 56);
        this.RightHornEnd.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.RightHornEnd.addBox(-7.0F, -8.0F, -0.5F, 1, 4, 1, 0.0F);
        this.FrontLeftPalm = new RendererModel(this, 0, 4);
        this.FrontLeftPalm.mirror = true;
        this.FrontLeftPalm.setRotationPoint(0.0F, 7.0F, 0.0F);
        this.FrontLeftPalm.addBox(0.0F, 5.0F, -1.0F, 1, 3, 3, 0.0F);
        this.FLBell = new RendererModel(this, 0, 0);
        this.FLBell.setRotationPoint(9.0F, 0.0F, 1.0F);
        this.FLBell.addBox(0.0F, 1.0F, -2.0F, 2, 2, 2, 0.0F);
        this.FrontRightFinger2 = new RendererModel(this, 0, 13);
        this.FrontRightFinger2.setRotationPoint(0.5F, 8.5F, 1.0F);
        this.FrontRightFinger2.addBox(-0.5F, -0.5F, 0.0F, 2, 1, 1, 0.0F);
        this.BackRightElbow = new RendererModel(this, 0, 0);
        this.BackRightElbow.setRotationPoint(-4.0F, 2.0F, 4.0F);
        this.BackRightElbow.addBox(0.0F, 0.0F, 0.0F, 0, 0, 0, 0.0F);
        this.setRotateAngle(BackRightElbow, 0.0F, 0.0F, 0.3141592653589793F);
        this.FrontRightFinger2End = new RendererModel(this, 0, 10);
        this.FrontRightFinger2End.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.FrontRightFinger2End.addBox(1.5F, -1.5F, 0.0F, 1, 2, 1, 0.0F);
        this.ChainLeftBack = new RendererModel(this, 44, 48);
        this.ChainLeftBack.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.ChainLeftBack.addBox(0.5F, 1.0F, -4.0F, 3, 16, 0, 0.0F);
        this.setRotateAngle(ChainLeftBack, 0.0F, -1.5707963267948966F, 0.0F);
        this.FrontHanging = new RendererModel(this, 54, 0);
        this.FrontHanging.mirror = true;
        this.FrontHanging.setRotationPoint(5.0F, 0.0F, 0.5F);
        this.FrontHanging.addBox(-2.0F, 1.0F, -0.5F, 4, 4, 1, 0.0F);
        this.BackLeftFinger2End = new RendererModel(this, 0, 10);
        this.BackLeftFinger2End.mirror = true;
        this.BackLeftFinger2End.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.BackLeftFinger2End.addBox(-2.5F, -1.5F, 0.0F, 1, 2, 1, 0.0F);
        this.FrontRightPalm = new RendererModel(this, 0, 4);
        this.FrontRightPalm.setRotationPoint(0.0F, 7.0F, 0.0F);
        this.FrontRightPalm.addBox(0.0F, 5.0F, -1.0F, 1, 3, 3, 0.0F);
        this.Chains = new RendererModel(this, 0, 0);
        this.Chains.setRotationPoint(0.0F, 3.0F, 0.0F);
        this.Chains.addBox(0.0F, 0.0F, 0.0F, 0, 0, 0, 0.0F);
        this.FrontLeftFinger2 = new RendererModel(this, 0, 13);
        this.FrontLeftFinger2.mirror = true;
        this.FrontLeftFinger2.setRotationPoint(0.5F, 8.5F, 1.0F);
        this.FrontLeftFinger2.addBox(-1.5F, -0.5F, 0.0F, 2, 1, 1, 0.0F);
        this.FrontRightPalm_1 = new RendererModel(this, 0, 4);
        this.FrontRightPalm_1.setRotationPoint(0.0F, 7.0F, 0.0F);
        this.FrontRightPalm_1.addBox(0.0F, 5.0F, -1.0F, 1, 3, 3, 0.0F);
        this.BackLeftFinger2 = new RendererModel(this, 0, 13);
        this.BackLeftFinger2.mirror = true;
        this.BackLeftFinger2.setRotationPoint(0.5F, 8.5F, 1.0F);
        this.BackLeftFinger2.addBox(-1.5F, -0.5F, 0.0F, 2, 1, 1, 0.0F);
        this.ChainRightFront = new RendererModel(this, 44, 48);
        this.ChainRightFront.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.ChainRightFront.addBox(0.5F, 1.0F, -4.0F, 3, 16, 0, 0.0F);
        this.setRotateAngle(ChainRightFront, 0.0F, 1.5707963267948966F, 0.0F);
        this.BackLeftThumb = new RendererModel(this, 8, 2);
        this.BackLeftThumb.mirror = true;
        this.BackLeftThumb.setRotationPoint(0.0F, 5.0F, 0.0F);
        this.BackLeftThumb.addBox(-1.0F, 0.0F, -2.0F, 2, 1, 2, 0.0F);
        this.FrontLeftFinger1End = new RendererModel(this, 0, 10);
        this.FrontLeftFinger1End.mirror = true;
        this.FrontLeftFinger1End.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.FrontLeftFinger1End.addBox(-2.5F, -1.5F, -1.0F, 1, 2, 1, 0.0F);
        this.BLBell = new RendererModel(this, 0, 0);
        this.BLBell.setRotationPoint(9.0F, 0.0F, 3.0F);
        this.BLBell.addBox(0.0F, 1.0F, 6.0F, 2, 2, 2, 0.0F);
        this.Head = new RendererModel(this, 0, 52);
        this.Head.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Head.addBox(-3.0F, -7.0F, -3.0F, 6, 6, 6, 0.0F);
        this.ChainBackLeft = new RendererModel(this, 38, 48);
        this.ChainBackLeft.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.ChainBackLeft.addBox(-3.5F, 1.0F, -4.0F, 3, 16, 0, 0.0F);
        this.setRotateAngle(ChainBackLeft, 0.0F, 3.141592653589793F, 0.0F);
        this.FrontRightFinger1End = new RendererModel(this, 0, 10);
        this.FrontRightFinger1End.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.FrontRightFinger1End.addBox(1.5F, -1.5F, -1.0F, 1, 2, 1, 0.0F);
        this.BackRightFinger1 = new RendererModel(this, 0, 13);
        this.BackRightFinger1.setRotationPoint(0.5F, 8.5F, 0.0F);
        this.BackRightFinger1.addBox(-0.5F, -0.5F, -1.0F, 2, 1, 1, 0.0F);
        this.ChainLeftFront = new RendererModel(this, 38, 48);
        this.ChainLeftFront.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.ChainLeftFront.addBox(-3.5F, 1.0F, -4.0F, 3, 16, 0, 0.0F);
        this.setRotateAngle(ChainLeftFront, 0.0F, -1.5707963267948966F, 0.0F);
        this.FrontLeftThumb = new RendererModel(this, 8, 2);
        this.FrontLeftThumb.mirror = true;
        this.FrontLeftThumb.setRotationPoint(0.0F, 5.0F, 0.0F);
        this.FrontLeftThumb.addBox(-1.0F, 0.0F, -2.0F, 2, 1, 2, 0.0F);
        this.LeftRornBase = new RendererModel(this, 56, 61);
        this.LeftRornBase.mirror = true;
        this.LeftRornBase.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.LeftRornBase.addBox(3.0F, -6.0F, -0.5F, 3, 2, 1, 0.0F);
        this.BackHanging = new RendererModel(this, 54, 0);
        this.BackHanging.setRotationPoint(5.0F, 0.0F, 0.5F);
        this.BackHanging.addBox(-2.0F, 1.0F, 8.5F, 4, 4, 1, 0.0F);
        this.ChainRightFront_1 = new RendererModel(this, 44, 48);
        this.ChainRightFront_1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.ChainRightFront_1.addBox(0.5F, 1.0F, -4.0F, 3, 16, 0, 0.0F);
        this.setRotateAngle(ChainRightFront_1, 0.0F, 1.5707963267948966F, 0.0F);
        this.ChainBackRight = new RendererModel(this, 44, 48);
        this.ChainBackRight.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.ChainBackRight.addBox(0.5F, 1.0F, -4.0F, 3, 16, 0, 0.0F);
        this.setRotateAngle(ChainBackRight, 0.0F, 3.141592653589793F, 0.0F);
        this.LeftHanging = new RendererModel(this, 54, 36);
        this.LeftHanging.setRotationPoint(0.5F, 1.0F, 5.0F);
        this.LeftHanging.addBox(-0.5F, 0.0F, -2.0F, 1, 8, 4, 0.0F);
        this.ChainFrontRight = new RendererModel(this, 38, 48);
        this.ChainFrontRight.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.ChainFrontRight.addBox(-3.5F, 1.0F, -4.0F, 3, 16, 0, 0.0F);
        this.BackRightFinger2 = new RendererModel(this, 0, 13);
        this.BackRightFinger2.setRotationPoint(0.5F, 8.5F, 1.0F);
        this.BackRightFinger2.addBox(-0.5F, -0.5F, 0.0F, 2, 1, 1, 0.0F);
        this.BackRightFinger1End = new RendererModel(this, 0, 10);
        this.BackRightFinger1End.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.BackRightFinger1End.addBox(1.5F, -1.5F, -1.0F, 1, 2, 1, 0.0F);
        this.BackRightFinger2End = new RendererModel(this, 0, 10);
        this.BackRightFinger2End.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.BackRightFinger2End.addBox(1.5F, -1.5F, 0.0F, 1, 2, 1, 0.0F);
        this.RightRornBase = new RendererModel(this, 56, 61);
        this.RightRornBase.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.RightRornBase.addBox(-6.0F, -6.0F, -0.5F, 3, 2, 1, 0.0F);
        this.BackLeftFinger1End = new RendererModel(this, 0, 10);
        this.BackLeftFinger1End.mirror = true;
        this.BackLeftFinger1End.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.BackLeftFinger1End.addBox(-2.5F, -1.5F, -1.0F, 1, 2, 1, 0.0F);
        this.BodyExtensionZ = new RendererModel(this, 36, 19);
        this.BodyExtensionZ.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.BodyExtensionZ.addBox(-2.0F, 1.0F, -5.0F, 4, 1, 10, 0.0F);
        this.BackLeftFinger1 = new RendererModel(this, 0, 13);
        this.BackLeftFinger1.mirror = true;
        this.BackLeftFinger1.setRotationPoint(0.5F, 8.5F, 0.0F);
        this.BackLeftFinger1.addBox(-1.5F, -0.5F, -1.0F, 2, 1, 1, 0.0F);
        this.Body = new RendererModel(this, 40, 11);
        this.Body.setRotationPoint(0.0F, 2.0F, 0.0F);
        this.Body.addBox(-3.0F, 0.0F, -3.0F, 6, 2, 6, 0.0F);
        this.RightHanging = new RendererModel(this, 54, 36);
        this.RightHanging.mirror = true;
        this.RightHanging.setRotationPoint(9.5F, 1.0F, 5.0F);
        this.RightHanging.addBox(-0.5F, 0.0F, -2.0F, 1, 8, 4, 0.0F);
        this.BackLeftPalm = new RendererModel(this, 0, 4);
        this.BackLeftPalm.mirror = true;
        this.BackLeftPalm.setRotationPoint(0.0F, 7.0F, 0.0F);
        this.BackLeftPalm.addBox(0.0F, 5.0F, -1.0F, 1, 3, 3, 0.0F);
        this.BodyBottom = new RendererModel(this, 24, 0);
        this.BodyBottom.setRotationPoint(-5.0F, 2.0F, -5.0F);
        this.BodyBottom.addBox(0.0F, 0.0F, 0.0F, 10, 1, 10, 0.0F);
        this.ChainRightBack = new RendererModel(this, 38, 48);
        this.ChainRightBack.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.ChainRightBack.addBox(-3.5F, 1.0F, -4.0F, 3, 16, 0, 0.0F);
        this.setRotateAngle(ChainRightBack, 0.0F, 1.5707963267948966F, 0.0F);
        this.FrontRightThumb = new RendererModel(this, 8, 2);
        this.FrontRightThumb.setRotationPoint(0.0F, 5.0F, 0.0F);
        this.FrontRightThumb.addBox(0.0F, 0.0F, -2.0F, 2, 1, 2, 0.0F);
        this.BodyBottom.addChild(this.BRBell);
        this.FrontRightPalm_1.addChild(this.BackRightThumb);
        this.LeftRornBase.addChild(this.LeftHornEnd);
        this.Body.addChild(this.BackLeftElbow);
        this.BodyBottom.addChild(this.FRBell);
        this.Head.addChild(this.Teeth);
        this.FrontRightPalm.addChild(this.FrontRightFinger1);
        this.FrontLeftFinger2.addChild(this.FrontLeftFinger2End);
        this.Body.addChild(this.FrontRightElbow);
        this.Body.addChild(this.FrontLeftElbow);
        this.Chains.addChild(this.ChainFrontLeft);
        this.Body.addChild(this.BodyExtensionY);
        this.FrontLeftPalm.addChild(this.FrontLeftFinger1);
        this.RightRornBase.addChild(this.RightHornEnd);
        this.FrontLeftElbow.addChild(this.FrontLeftPalm);
        this.BodyBottom.addChild(this.FLBell);
        this.FrontRightPalm.addChild(this.FrontRightFinger2);
        this.Body.addChild(this.BackRightElbow);
        this.FrontRightFinger2.addChild(this.FrontRightFinger2End);
        this.Chains.addChild(this.ChainLeftBack);
        this.BodyBottom.addChild(this.FrontHanging);
        this.BackLeftFinger2.addChild(this.BackLeftFinger2End);
        this.FrontRightElbow.addChild(this.FrontRightPalm);
        this.Body.addChild(this.Chains);
        this.FrontLeftPalm.addChild(this.FrontLeftFinger2);
        this.BackRightElbow.addChild(this.FrontRightPalm_1);
        this.BackLeftPalm.addChild(this.BackLeftFinger2);
        this.Chains.addChild(this.ChainRightFront);
        this.BackLeftPalm.addChild(this.BackLeftThumb);
        this.FrontLeftFinger1.addChild(this.FrontLeftFinger1End);
        this.BodyBottom.addChild(this.BLBell);
        this.Chains.addChild(this.ChainBackLeft);
        this.FrontRightFinger1.addChild(this.FrontRightFinger1End);
        this.FrontRightPalm_1.addChild(this.BackRightFinger1);
        this.Chains.addChild(this.ChainLeftFront);
        this.FrontLeftPalm.addChild(this.FrontLeftThumb);
        this.Head.addChild(this.LeftRornBase);
        this.BodyBottom.addChild(this.BackHanging);
        this.Chains.addChild(this.ChainRightFront_1);
        this.Chains.addChild(this.ChainBackRight);
        this.BodyBottom.addChild(this.LeftHanging);
        this.Chains.addChild(this.ChainFrontRight);
        this.FrontRightPalm_1.addChild(this.BackRightFinger2);
        this.BackRightFinger1.addChild(this.BackRightFinger1End);
        this.BackRightFinger2.addChild(this.BackRightFinger2End);
        this.Head.addChild(this.RightRornBase);
        this.BackLeftFinger1.addChild(this.BackLeftFinger1End);
        this.Body.addChild(this.BodyExtensionZ);
        this.BackLeftPalm.addChild(this.BackLeftFinger1);
        this.BodyBottom.addChild(this.RightHanging);
        this.BackLeftElbow.addChild(this.BackLeftPalm);
        this.Body.addChild(this.BodyBottom);
        this.Chains.addChild(this.ChainRightBack);
        this.FrontRightPalm.addChild(this.FrontRightThumb);
    }

    @Override
    public void render(T entityIn, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch, float scale) { 
        this.Head.render(scale);
        this.Body.render(scale);
    }

    /**
     * This is a helper function from Tabula to set the rotation of model parts
     */
    public void setRotateAngle(RendererModel modelRenderer, float x, float y, float z) {
        modelRenderer.rotateAngleX = x;
        modelRenderer.rotateAngleY = y;
        modelRenderer.rotateAngleZ = z;
    }
}
